### ISSUE TITLE
Set up auto deploy to Google AppEngine

### ISSUE THREAD

**Issue by markroth8** [dsjoerg/ca_visit_tracking#15]
Need to set up Google Cloud Build

**Comment by dsjoerg** [comment]
Auto deploy scares me because we don't have automated testing. Would rather have manual QA before deploy, or at least the oppty to do so based on what's being committed.

Let's discuss in this issue if you have other thoughts on this.

**Comment by markroth8** [comment]
Another way to handle this is to keep master sacred and only merge to master after QA.

**Comment by markroth8** [comment]
We decided against doing this and did #53 instead.
