### ISSUE TITLE
support@visitdata.org email forwarded to a list of us

### ISSUE THREAD

**Issue by dsjoerg** [dsjoerg/ca_visit_tracking#2]
If this is going to be in the hands of a few hundred county health officers, they're going to have questions & need a way to reach someone.
Let's have an email address they can reach out to, and have it forward to a list of email addresses.

@markroth8 is this something you can do in the Google Domain console?

**Comment by markroth8** [comment]
support@visitdata.org now forwards to visitdata-org-support@googlegroups.com.
Added markroth8@gmail.com and dsjoerg@gmail.com to the google group.
