### ISSUE TITLE
style: make it look more official / trustworthy

### ISSUE THREAD

**Issue by dsjoerg** [dsjoerg/ca_visit_tracking#4]

**Comment by ajanian** [comment]
I think the first version looks alright on desktop.  Still need to do the following:
- work with @markroth8 to template this so I don't copy/paste the <html>...<body> </body></html> on every page
- make it work on mobile

**Comment by dsjoerg** [comment]
@robertobuso great job, this looks like a real thing now, definitely more trustworthy.
