### ISSUE TITLE
Kara request: deselect/select all counties in the chart

### ISSUE THREAD

**Issue by dsjoerg** [dsjoerg/ca_visit_tracking#45]
A way to toggle "delect/select all counties" (to save clicking ~58 times on some of the venue graphs)

**Comment by robertobuso** [comment]
I can take this one.

**Comment by dsjoerg** [comment]
I think this one requires jumping in to the Highcharts API.

**Comment by robertobuso** [comment]
Yup, I've included a Show/Hide in the legend, created an event in plotOptions.series to listen to a click in the legend and if it's Show/Hide to either show or hide all series depending on the current value of the boolean. It's almost ready to show.

**Comment by dsjoerg** [comment]
holy moly!

**Comment by dsjoerg** [comment]
@robertobuso did it
