### ISSUE TITLE
Add a version number on the site somewhere so we can see which version is in production

### ISSUE THREAD

**Issue by dsjoerg** [dsjoerg/ca_visit_tracking#53]
I am trying to figure out how much non-deployed stuff is in github and I have no idea which version I deployed.

Maybe put the github hash of the latest commit on the site somewhere or even hidden in the HTML of the template?

**Comment by markroth8** [comment]
Another way to do this is #15. Which would you rather have, @dsjoerg?

**Comment by dsjoerg** [comment]
Auto deploy scares me because we don't have automated testing. Would rather have manual QA before deploy, or at least the oppty to do so based on what's being committed.

So would rather have this one.
