### ISSUE TITLE
Make whole-state data available in the County dropdown; show it by default?

### ISSUE THREAD

**Issue by dsjoerg** [dsjoerg/ca_visit_tracking#62]
Foursquare has given us whole-state data alongside individual County data.
Make it available in the visitdata.org UI

**Comment by ajanian** [comment]
@dsjoerg where is the whole state data?  I can't seem to find that in any of the files

**Comment by dsjoerg** [comment]
Havent posted it yet

**Comment by dsjoerg** [comment]
OK it's at https://www.dropbox.com/s/yqeu1mlwrq4ugjg/march-data-20200331.tar.gz?dl=0

**Comment by dsjoerg** [comment]
And I committed a script to process the county-level data that you might find helpful
