### ISSUE TITLE
Title is wrong for this >65 GDS chart

### ISSUE THREAD

**Issue by dsjoerg** [dsjoerg/ca_visit_tracking#66]
https://datastudio.google.com/u/0/reporting/1hV7FGnBPuTeDrZ0BBsaZjimLjYt7X792/page/J0GKB

it says all ages but its >65 right?
the last one.

**Comment by ajanian** [comment]
The last and the second to last were wrong.  The page was right in the nav but the title at the top of the page was wrong.
