### ISSUE TITLE
single point of entry, permitting navigation to all available information

### ISSUE THREAD

**Issue by dsjoerg** [dsjoerg/ca_visit_tracking#7]
right now there are three independent ways to look at the data:

* https://visitdata.org/
* https://visitdata.org/bydate.html
* https://visitdata.org/bydate.html?datafilename=rawcatsfixed

And no way to navigate between them.

**Comment by ajanian** [comment]
This should be completed with #14

**Comment by ajanian** [comment]
all 3 of those are linked from the nav bar on the left
