### ISSUE TITLE
visitdata.org is rendering sideways on my android device

### ISSUE THREAD

**Issue by dsjoerg** [dsjoerg/ca_visit_tracking#84]
from david shim

**Comment by ajanian** [comment]
this was intentional when the mobile was built I think, right?

**Comment by robertobuso** [comment]
Yes, like @ajanian says this was a specific request: to force the mobile view to always be landscape. I agree that it's not the best solution. Perhaps I can add a modal asking the user to turn the phone sideways when it's portrait?

**Comment by dsjoerg** [comment]
On further thought, forcing landscape is not what websites typically do. I've never used a website that did that, so people will find it surprising/confusing.

I'm not sure how other websites handle it, but they don't do that.

Roberto, whatever you think is best here.

**Comment by robertobuso** [comment]
Sounds good, I'm on it.
